version: '2'
services:
    picaditos-wa:
        build: .
        environment:
          API_URL: 'picaditos-api'
          API_PORT: '5000'
          API_ENTRY: 'graphql'

        command: "npm start\t--port 3000"
        ports:
            - '3000:3000'
